server:
  port: 8888  
spring: 
  application:
    name: job-service
zuul:
  routes:
    POC_4:
      path: /poc/**
      url: http://localhost:8086/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
     
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
       hostname: localhost
    server:
       enableSelfPreservation: false
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration        