server:
  port: 8083
zuul:
  routes:
   job-service:
      path: /job/**
      service-id: job-service
      strip-prefix: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka
spring:
  application:
    name: zuul-gateway 