#server.port: 9000
spring.application.name: zuul - gateway
server:
  port: 9000
zuul:
  routes:
   spring-microservice-jpa-user:
      path: /**
      service-id: spring-microservice-jpa
#      url: http://localhost:9090/
#   spring-microservice-jpa-job:
#      path: /**
#      service-id: spring-microservice-jpa
#      url: http://localhost:9090/
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: zuul-gateway      